### ISSUE TITLE
Build issue with cometchat android SDK

### ISSUE THREAD

**Issue by pradeeprkotha** [cometchat-pro-samples/android-java-chat-app#13]
Hi Team,

I am getting following error.
class file for com.google.android.gms.common.internal.safeparcel.zza not found

Please help me out. it seems some google play services version mismatch.

**Comment by yadavmangesh** [comment]
Hey @pradeeprkotha 
Seems like you are using an older version of the sample App, Can you please pull the latest code and check whether you are getting the same problem.

**Comment by pradeeprkotha** [comment]
Hi thanks for getting back to me.

May I know the latest version of the Gradle plugin please?. Thanks

**Comment by yadavmangesh** [comment]
@pradeeprkotha 
The Gradle distribution in our sample App is 5.1.1.
But your problem is due to play service plugin which was used in our older version of the sample App which is now removed in the lasted code
