### ISSUE TITLE
About use your codes.

### ISSUE THREAD

**Issue by Mrtckr008** [cometchat-pro-samples/android-java-chat-app#14]
Hello, Mr. Yadavmangesh,
First of all, I want to introduce myself. I'm a junior mobile developer in Turkey. The greatest purpose of my life is to have a very good career like you. So of course I want to improve myself. I'm working at company as a mobile developer. In my free time I am trying to make  new projects and thinking about new ideas for the projects. Anyway, I want to make a new project, but I need to use your demo project code. I have some questions.
1- Will this project always be ready? (e.g Can I use it next year?)
2- Is there any limit for the demo project? ("e.g limit of 1000 requests in 1 day") (I used to the project demo on my phone and I know the general limits)
3- Is this demo project completely free?

By the way, I'm completely changing the application layouts, it will be a very different project from yours. I just need to use group voice chat.
Thank you for sharing this code. I have a so proud to contact with you.
I hope you will be help to me about my questions.
Best Regards.

**Comment by anantgarg** [comment]
Hi @Mrtckr008!

You can use CometChat Pro for development as long as you like. And let us know if you have any questions. We are happy to help.
