### ISSUE TITLE
Calls are not ending properly

### ISSUE THREAD

**Issue by im-ng** [cometchat-pro-samples/android-java-chat-app#15]
- Dropping an ongoing call is not clearing the channel for further audio/video calls. Often we end up with this screen which forces to drop a newly connected call.

- It is reproducible with current repo itself.

![call_issue](https://user-images.githubusercontent.com/2039564/63604812-51636b80-c5ea-11e9-93ba-0e6bde15a77d.png)

**Comment by yadavmangesh** [comment]
Hey, @ng28  We have released a fix in our new SDK version 1.8.5. you can pull the latest changes from our repository
