### ISSUE TITLE
Issue with image compression when user takes a photo with camera and sends it

### ISSUE THREAD

**Issue by theodoulos** [cometchat-pro-samples/android-java-chat-app#16]
There seems to be a problem when a user takes a photo within the chat and sends it directly. The picture gets pixelated (compressed) . When a picture is send as an attachment from the chat it works fine.

**Comment by yadavmangesh** [comment]
Hey, @theodoulos   We have released a fix in our new SDK version 1.8.5. you can pull the latest changes from our repository
