### ISSUE TITLE
[SDK-7.33.+] Video and Call functionality is not working 

### ISSUE THREAD

**Issue by ankit-trantor** [cometchat-pro-samples/android-java-chat-app#18]
Failed to log event: Video Conference Call
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.flurry.sdk.df com.flurry.sdk.ck.a(java.lang.Class)' on a null object reference
**Logs (Error Logs)**
- Error Log
- Debug Log
 
**Additional context**

**Comment by darshanbhanushali** [comment]
Hi @ankit-trantor ,

Seems like this issue is related to Cometchat GO. Please send your feedback on support@cometchat.com
