### ISSUE TITLE
I installed and compiled from GUTHUB Source and uploaded to Google Play however it says NO DEVICES are compatible with it

### ISSUE THREAD

**Issue by squizzster** [cometchat-pro-samples/android-java-chat-app#24]
I could add my build files if you need.
I've tried it twice now and always does the same thing... the APK runs on test devices just fine.
It uploads and is fine for PlayStore however it shows as below.

![image](https://user-images.githubusercontent.com/62567353/109433909-a1569600-7a0a-11eb-98de-9812e5c98e1f.png)
![image](https://user-images.githubusercontent.com/62567353/109433948-c6e39f80-7a0a-11eb-981a-da726f246cd9.png)

I've updated all tools, SDK's and updates to the latest versions.

Thanks!

**Comment by squizzster** [comment]
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.cometchat.pro.uikit"
    android:versionCode="1"
    android:versionName="1.0" >

    <uses-sdk
        android:minSdkVersion="21"
        android:targetSdkVersion="29" />

    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

    <uses-feature android:name="android.hardware.camera2.full" />

    <application
        android:hardwareAccelerated="true"
        android:requestLegacyExternalStorage="true"
        android:usesCleartextTraffic="true"
        tools:node="merge"
        tools:targetApi="m" >
        <activity android:name="com.cometchat.pro.uikit.ui_components.messages.extensions.Collaborative.CometChatCollaborativeActivity" />
        <activity android:name="com.cometchat.pro.uikit.ui_components.messages.extensions.Reactions.CometChatReactionInfoActivity" />
        <activity android:name="com.cometchat.pro.uikit.ui_components.messages.media_view.CometChatMediaViewActivity" />
        <activity android:name="com.cometchat.pro.uikit.ui_components.messages.message_information.CometChatMessageInfoScreenActivity" />
        <activity android:name="com.cometchat.pro.uikit.ui_components.calls.call_manager.CometChatStartCallActivity" />
        <activity
            android:name="com.cometchat.pro.uikit.ui_components.messages.thread_message_list.CometChatThreadMessageListActivity"
            android:windowSoftInputMode="adjustResize" />
        <activity android:name="com.cometchat.pro.uikit.ui_components.groups.banned_members.CometChatBanMembersActivity" />
        <activity
            android:name="com.cometchat.pro.uikit.ui_components.calls.call_manager.CometChatCallActivity"
            android:screenOrientation="portrait"
            android:theme="@style/TransparentCompat" />
        <activity
            android:name="com.cometchat.pro.uikit.ui_components.calls.call_list.CometChatNewCallList"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.cometchat.pro.uikit.ui_components.messages.forward_message.CometChatForwardMessageActivity"
            android:screenOrientation="portrait" >
            <intent-filter>
                <action android:name="android.intent.action.SEND" />

                <category android:name="android.intent.category.DEFAULT" />

                <data android:mimeType="image/*" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.SEND" />

                <category android:name="android.intent.category.DEFAULT" />

                <data android:mimeType="text/plain" />
            </intent-filter>
        </activity>

        <meta-data
            android:name="com.cometchat.pro.uikit"
            android:value="${file_provider}" />

        <activity
            android:name="com.cometchat.pro.uikit.ui_components.groups.create_group.CometChatCreateGroupActivity"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustPan" />
        <activity
            android:name="com.cometchat.pro.uikit.ui_components.userprofile.privacy_security.CometChatMorePrivacyActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.cometchat.pro.uikit.ui_components.users.block_users.CometChatBlockUserListActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.cometchat.pro.uikit.ui_components.groups.group_details.CometChatGroupDetailActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.cometchat.pro.uikit.ui_components.groups.add_members.CometChatAddMembersActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.cometchat.pro.uikit.ui_components.groups.admin_moderator_list.CometChatAdminModeratorListActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.cometchat.pro.uikit.ui_components.groups.group_members.CometChatGroupMemberListActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.cometchat.pro.uikit.ui_components.users.user_details.CometChatUserDetailScreenActivity"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustResize" />
        <activity
            android:name="com.cometchat.pro.uikit.ui_components.cometchat_ui.CometChatUI"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustResize" />
        <activity
            android:name="com.cometchat.pro.uikit.ui_components.messages.message_list.CometChatMessageListActivity"
            android:parentActivityName="com.cometchat.pro.uikit.ui_components.cometchat_ui.CometChatUI"
            android:screenOrientation="portrait" />

        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${file_provider}.provider"
            android:exported="false"
            android:grantUriPermissions="true" >
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_path" />
        </provider>
    </application>

</manifest>

**Comment by darshanbhanushali** [comment]
Hi,

Can you please remove `<uses-feature android:name="android.hardware.camera2.full" />` from `AndroidManifest.xml` and try again.?

**Comment by squizzster** [comment]
![image](https://user-images.githubusercontent.com/62567353/109577233-2f0ab200-7aed-11eb-89ed-440d90393c4d.png)

**Comment by squizzster** [comment]
Yes, that has fixed it.
Thank you very much.

Do you know why?

**Comment by darshanbhanushali** [comment]
Yes,
Because that makes the app to run only on device those have atleast one camera. We have removed it and updated our uiKit library.
