### ISSUE TITLE
Error occurred

### ISSUE THREAD

**Issue by Nilkesh310307** [cometchat-pro-samples/android-java-chat-app#25]
No cached version of com.cometchat:pro-android-chat-sdk:2.3.4 available for offline mode.

**Comment by darshanbhanushali** [comment]
Hi @Nilkesh310307 ,

Can you please elaborate the issue or share the error log, so we can identify the issue and help you to resolve it.

**Comment by proveshapyne** [comment]
Hi @Nilkesh310307,

I am closing this ticket due to inactivity. If you need further assistance with this, please feel free to write to us at help@cometchat.com.
Thank you.

Regards,
Provesha
