### ISSUE TITLE
Uikit imports not working

### ISSUE THREAD

**Issue by neerajnsp** [cometchat-pro-samples/android-java-chat-app#33]
Uikit imports are giving me error
![Screenshot 2022-08-30 at 6 29 37 PM](https://user-images.githubusercontent.com/65755340/187442967-ddd6fb10-6969-4cd5-a7be-2a458186ad99.png)

**Comment by rohit-cometchat** [comment]
Hi, please check this [https://github.com/cometchat-pro/android-kotlin-chat-app/blob/69b1765c896aa67b65a52e6fc72723d466e2b898/app/build.gradle#L65](url)
