### ISSUE TITLE
Audio Message still not working (Android UI JAVA)

### ISSUE THREAD

**Issue by Flipspot** [cometchat-pro-samples/android-java-chat-app#5]
We have pulled the changes however there are still a lot of issues.

1) When click the audio button it's not palying most of the time (both side)
2) Audio message recording time showing wrong
3) All voice message always update the last audio recording time
4) Sometimes recording time showing very long

https://gyazo.com/5d564700f05475ff81cb1eeb99a78ed1
https://gyazo.com/6ead71c3be31356938aee5d081c12d1d

You can view these issues with the Gyazo shared link above. Please find a resolution for this so we can get audio message working.

**Comment by yadavmangesh** [comment]
@Flipspot 
We are looking into it. We'll fix this issue as soon as possible

**Comment by Flipspot** [comment]
Okay please update me asap.

**Comment by Flipspot** [comment]
has this been resolved

**Comment by yadavmangesh** [comment]
@Flipspot  
We are working on it with priority. We have identified the cause of the issue 
it will require a day or two to  fix it

**Comment by Flipspot** [comment]
ok we will wait.

**Comment by Flipspot** [comment]
Has this been resolved yet, been over 2 days.

**Comment by yadavmangesh** [comment]
@Flipspot 
we have updated the repository. Please pull the latest change and see if your issue is resolved.
Delete the CometChat Pro Folder from your Phone Storage as some of the previous audio files were not of the proper format.

**Comment by Flipspot** [comment]
Ok will do and update you.

**Comment by Flipspot** [comment]
My developer is asking what files are new, and how to pull the latest changes (and which files to pull).

**Comment by adityagokula2210** [comment]
@Flipspot 
You can check the commits using the below link to check the files modified:
https://github.com/cometchat-pro-samples/android-java-chat-app/commits/master

You can also refer to the below links for more information:

https://help.github.com/en/articles/differences-between-commit-views

https://help.github.com/en/articles/fetching-a-remote

Hope this helps.
Thanks
