### ISSUE TITLE
Android java SDK Speed issue

### ISSUE THREAD

**Issue by Flipspot** [cometchat-pro-samples/android-java-chat-app#6]
When i send a message on the android java sdk, it takes 2-3seconds for it to show. It should load instantly, or max within a second, like other chat modules.

We tried fixing this but i think we need you guys to resolve this.

**Comment by Flipspot** [comment]
Any solution to this?

Thanks

**Comment by adityagokula2210** [comment]
@Flipspot 
As mentioned in Issue [#7], this issue can also be resolved by adding a local database to the app. 
In this case, you need to add the message sent to the local database immediately and in the UI inform the user that the message is not yet sent and is in a pending state . And once the success for the message sent is received you can update the status of the message in the local database as sent and update the UI accordingly to inform the user that the message is sent successfully.

We do plan to release sample apps with local storage enabled in the coming weeks. However, we do not have an exact timeline at the moment.

Hope this helps.
Thanks
