### ISSUE TITLE
If you switch between chat windows, sometimes the entire chat screen just goes blank 

### ISSUE THREAD

**Issue by Flipspot** [cometchat-pro-samples/android-java-chat-app#7]
See image for more info - https://i.gyazo.com/9645bf29e2a0b592a771814aae9665ff.png

We tried fixing this but cannot find the source of the issue.

**Comment by Flipspot** [comment]
Any solution to this?

Thanks

**Comment by adityagokula2210** [comment]
@Flipspot ,

At the moment, local database is not implemented in  the sample apps. Thus, every time a new chat window is opened, the messages are fetched from the server using API calls which leads to a delay.

The delay is dependent on the network speed.
You can achieve this at your end by simply adding a local database like SQLite or some ORM like Sugar, Google Rooms etc.

All you need to do is save all the messages fetched in the local database and while displaying messages, check if the messages are present in the local database. If messages are available from the local database, display them, else use the CometChat methods to fetch the messages.

We do plan to release sample apps with local storage enabled in the coming weeks. However, we do not have an exact timeline at the moment.

Hope this helps.
Thanks

**Comment by Flipspot** [comment]
Nearly 80% of the time, when i click on a chat, the entire screen is white, and even after 1minute, it is still ALL white, and conversation is not showing. I have 200+ mbps and still this issue is happening.

We need to resolve this, we can't have chats disappearing and not coming back, this is the basic functionality of a chat app

What is the solution to this

**Comment by adityagokula2210** [comment]
@Flipspot 

Can you please confirm the version of the SDK you are using?
Also, we have tried testing this scenario at our end with the latest SDK version (1.3.0) and we are not able to replicate this issue. We would need some more inputs from your side so that we can debug the issue better.
Can you please check if there is a specific scenario when this issue occurs or does this happen every time a new chat screen is launched.
It would be great if you could share a video of the same issue so that we can check the steps to get the issue at our end.

Thanks

**Comment by Flipspot** [comment]
I will ask my developer for more information.

Right now we are integrating the latest SDK into our flipspot APK. When i click on certain chats from the chats page, it just shows blank like this https://i.gyazo.com/9645bf29e2a0b592a771814aae9665ff.png. Even after 1-2 minutes it remains like this. It can be from completely new chats, it's still not showing.

I will ask my developer for more information, but this is all i can share for now.

**Comment by ranjanravi85** [comment]
Closing this issue, hope your issue has been resolved.
