### ISSUE TITLE
Changing Call pre-text

### ISSUE THREAD

**Issue by Flipspot** [cometchat-pro-samples/android-java-chat-app#9]
If I decline a call, the text ‘decline’ shows, instead it should show “Call cancelled,” and in the chat it shows as “initiated and cancelled,” it should say “Call initiated” and “Call cancelled.” And in the chat it says “Missed Call,” when it should be “username missed your call.”

**Comment by yadavmangesh** [comment]
@Flipspot 
You can make your custom message as you required by using [`Call`](https://prodocs.cometchat.com/docs/android-appendix#section-call) object. You can use  `callInitiator` , `callReceiver` and  `callStatus` of call object to make your own message

**Comment by Flipspot** [comment]
thanks!!!!
